import { NextResponse } from "next/server";
import { readdir, stat } from "fs/promises";
import path from "path";

// Mock available skills from "clawhub" for discovery
// In a real implementation, this would fetch from clawhub.com API
const CLAWHUB_FEATURED = [
  {
    id: "clawhub:file-processor",
    name: "file-processor",
    description: "Process and transform files in bulk. Supports CSV, JSON, XML, images, and more.",
    category: "utility",
    emoji: "📁",
    version: "2.1.0",
    author: "clawhub-team",
    downloads: 15420,
    rating: 4.7,
    trending: true,
    isNew: false,
    tags: ["files", "automation", "batch"],
  },
  {
    id: "clawhub:web-scraper",
    name: "web-scraper",
    description: "Scrape and extract structured data from websites using CSS selectors or AI.",
    category: "web",
    emoji: "🕷️",
    version: "1.4.2",
    author: "community",
    downloads: 8930,
    rating: 4.5,
    trending: true,
    isNew: false,
    tags: ["scraping", "web", "data"],
  },
  {
    id: "clawhub:pdf-tools",
    name: "pdf-tools",
    description: "Extract text, merge, split, and annotate PDF documents.",
    category: "utility",
    emoji: "📄",
    version: "3.0.1",
    author: "community",
    downloads: 12100,
    rating: 4.6,
    trending: false,
    isNew: false,
    tags: ["pdf", "documents"],
  },
  {
    id: "clawhub:sql-agent",
    name: "sql-agent",
    description: "Natural language to SQL queries. Connect to PostgreSQL, MySQL, SQLite.",
    category: "data",
    emoji: "🗄️",
    version: "1.2.0",
    author: "clawhub-team",
    downloads: 6750,
    rating: 4.8,
    trending: true,
    isNew: true,
    tags: ["sql", "database", "data"],
  },
  {
    id: "clawhub:email-assistant",
    name: "email-assistant",
    description: "Compose, summarize, and categorize emails. Works with Gmail and Outlook.",
    category: "productivity",
    emoji: "✉️",
    version: "2.0.3",
    author: "community",
    downloads: 9800,
    rating: 4.4,
    trending: false,
    isNew: false,
    tags: ["email", "productivity"],
  },
  {
    id: "clawhub:code-review",
    name: "code-review",
    description: "Automated code review with security scanning, style checks, and suggestions.",
    category: "coding",
    emoji: "🔍",
    version: "1.1.0",
    author: "clawhub-team",
    downloads: 5420,
    rating: 4.9,
    trending: true,
    isNew: true,
    tags: ["coding", "review", "security"],
  },
  {
    id: "clawhub:data-viz",
    name: "data-viz",
    description: "Generate charts, graphs, and visualizations from data files or API responses.",
    category: "data",
    emoji: "📊",
    version: "1.0.5",
    author: "community",
    downloads: 4100,
    rating: 4.3,
    trending: false,
    isNew: true,
    tags: ["charts", "visualization", "data"],
  },
  {
    id: "clawhub:meeting-notes",
    name: "meeting-notes",
    description: "Transcribe and summarize meeting recordings. Extracts action items automatically.",
    category: "productivity",
    emoji: "📝",
    version: "2.2.1",
    author: "clawhub-team",
    downloads: 11200,
    rating: 4.6,
    trending: false,
    isNew: false,
    tags: ["meetings", "transcription", "productivity"],
  },
];

export async function GET() {
  // In production: fetch from clawhub.com/api/skills?featured=true&limit=20
  return NextResponse.json({
    skills: CLAWHUB_FEATURED,
    count: CLAWHUB_FEATURED.length,
    source: "clawhub",
    trending: CLAWHUB_FEATURED.filter((s) => s.trending).map((s) => s.id),
    new: CLAWHUB_FEATURED.filter((s) => s.isNew).map((s) => s.id),
  });
}
